 

/** *
* @author Анастасия
*/
public class AssemblerUI extends javax.swing.JFrame
{
 /**
 * Creates new form CourseWorkUI
 */
 public AssemblerUI() {

 initComponents();
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {
 ResultDialog = new javax.swing.JDialog();
 OKButton = new javax.swing.JButton();
 jScrollPane1 = new javax.swing.JScrollPane();
 ResultText = new javax.swing.JTextArea();
 Start = new javax.swing.JButton();
 JScrollPanel = new javax.swing.JScrollPane();
 CodeContainer = new javax.swing.JTextArea();
 ResultDialog.setMinimumSize(new java.awt.Dimension(700, 230));
 OKButton.setText("OK");
 OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
 public void mouseClicked(java.awt.event.MouseEvent evt) {
 OKButtonMouseClicked(evt);
 }
 });
 jScrollPane1.setEnabled(false);
 ResultText.setEditable(false);
 ResultText.setColumns(20);
 ResultText.setRows(5);
 ResultText.setBorder(null);
 jScrollPane1.setViewportView(ResultText);
 javax.swing.GroupLayout ResultDialogLayout = new javax.swing.GroupLayout(ResultDialog.getContentPane());
 ResultDialog.getContentPane().setLayout(ResultDialogLayout);
 ResultDialogLayout.setHorizontalGroup(
 ResultDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(ResultDialogLayout.createSequentialGroup()
 .addContainerGap()
 .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
 .addContainerGap())
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultDialogLayout.createSequentialGroup()
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 .addComponent(OKButton)
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
 );
 ResultDialogLayout.setVerticalGroup(
 ResultDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultDialogLayout.createSequentialGroup()
 .addContainerGap()
 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 .addComponent(OKButton)
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
 );
 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 setName("AssemblerTranslator"); // NOI18N
 Start.setText("Start");
 Start.addMouseListener(new java.awt.event.MouseAdapter() {
 public void mouseClicked(java.awt.event.MouseEvent evt) {
 StartMouseClicked(evt);
 }
 });
 CodeContainer.setColumns(20);
 CodeContainer.setRows(5);
 JScrollPanel.setViewportView(CodeContainer);
 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
 getContentPane().setLayout(layout);
 layout.setHorizontalGroup(
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
 .addContainerGap()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
 .addComponent(JScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
 .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE))
 .addContainerGap())
 );
 layout.setVerticalGroup(
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addContainerGap()
 .addComponent(JScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
 .addGap(18, 18, 18)
 .addComponent(Start)
 .addContainerGap())
 );
 pack();
 }// </editor-fold>//GEN-END:initComponents
 private void StartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseClicked
 String result;
 if (CodeContainer.getText().isBlank()) {
 result = "Code container is empry. Please, write something";
 } else {
 result = new Assembler(CodeContainer.getText()).compile();
 }
 ResultText.setText(result);
 ResultDialog.setVisible(true);
 }//GEN-LAST:event_StartMouseClicked
 private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
 ResultDialog.setVisible(false);
 }//GEN-LAST:event_OKButtonMouseClicked
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {
 java.util.logging.Logger.getLogger(AssemblerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {
 java.util.logging.Logger.getLogger(AssemblerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {
 java.util.logging.Logger.getLogger(AssemblerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
 java.util.logging.Logger.getLogger(AssemblerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new AssemblerUI().setVisible(true);
 }
 });
 }
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JTextArea CodeContainer;
 private javax.swing.JScrollPane JScrollPanel;
 private javax.swing.JButton OKButton;
 private javax.swing.JDialog ResultDialog;
 private javax.swing.JTextArea ResultText;
 private javax.swing.JButton Start;
 private javax.swing.JScrollPane jScrollPane1;
 // End of variables declaration//GEN-END:variables
}